apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluidai-app
  namespace: fluidai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluidai-app
  template:
    metadata:
      labels:
        app: fluidai-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: metejas/fluidai-demo:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3